name: llm-training-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - ipykernel
  - pip:
      - openai
      - langchain
      - langchain-community
      - langchain-openai
      - beautifulsoup4
